version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      bash -c ' python manage.py makemigrations
      && python manage.py migrate
      && python manage.py collectstatic --no-input
      && gunicorn config.wsgi:application --bind 0.0.0.0:8000'
    expose:
      - 8000
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    env_file:
      - .env.prod
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/app/static
      - media_volume:/app/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  static_volume:
  media_volume: