# Generated by Django 4.1.4 on 2023-02-09 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='student full name')),
                ('school_parallel', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11')], max_length=2, verbose_name='school parallel')),
                ('school_сlass', models.CharField(choices=[('а', 'а'), ('б', 'б'), ('в', 'в')], max_length=2, verbose_name='school сlass')),
            ],
        ),
    ]
