# Generated by Django 4.1.4 on 2023-01-13 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('students_name', models.CharField(max_length=100)),
                ('other', models.TextField()),
                ('teachers_name', models.CharField(max_length=100)),
                ('stage', models.CharField(choices=[('Школьный', 'Школьный'), ('Районный', 'Районный'), ('Городской', 'Городской'), ('Региональный', 'Региональный'), ('Всероссийский', 'Всероссийский'), ('Международный', 'Международный')], max_length=25)),
                ('direction', models.CharField(choices=[('Спорт', 'Спорт'), ('Образование', 'Образование'), ('Исскуство', 'Исскуство'), ('Культура', 'Культура'), ('Социальное', 'Социальное'), ('Олимпиада', 'Олимпиада')], max_length=25)),
                ('subject', models.CharField(max_length=100)),
                ('school_сlass', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('1 место', '1 место'), ('2 место', '2 место'), ('3 место', '3 место'), ('Призёр', 'Призёр'), ('Победитель', 'Победитель'), ('Лауреат', 'Лауреат'), ('Участник', 'Участник'), ('Дипломат', 'Дипломат')], max_length=25)),
            ],
        ),
    ]
