# Generated by Django 4.1.4 on 2023-01-17 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('event_date', models.DateField()),
                ('title', models.CharField(max_length=100)),
                ('students_name', models.CharField(max_length=100)),
                ('other', models.TextField(blank=True, null=True)),
                ('teachers_name', models.CharField(blank=True, max_length=100, null=True)),
                ('stage', models.CharField(choices=[('Школьный', 'Школьный'), ('Районный', 'Районный'), ('Городской', 'Городской'), ('Региональный', 'Региональный'), ('Всероссийский', 'Всероссийский'), ('Международный', 'Международный')], max_length=25)),
                ('direction', models.CharField(choices=[('Спорт', 'Спорт'), ('Образование', 'Образование'), ('Исскуство', 'Исскуство'), ('Культура', 'Культура'), ('Социальное', 'Социальное'), ('Олимпиада', 'Олимпиада')], max_length=25)),
                ('subject', models.CharField(choices=[('Русский язык', 'Русский язык'), ('Литературное чтение', 'Литературное чтение'), ('Математика', 'Математика'), ('Окружающий мир', 'Окружающий мир'), ('Музыка', 'Музыка'), ('ИЗО', 'ИЗО'), ('Технология', 'Технология'), ('Физическая культура', 'Физическая культура'), ('Английский язык', 'Английский язык'), ('ОРКСЭ', 'ОРКСЭ'), ('Литература', 'Литература'), ('История', 'История'), ('Обществознание', 'Обществознание'), ('География', 'География'), ('Биология', 'Биология'), ('ОБЖ', 'ОБЖ'), ('Экономика', 'Экономика'), ('Технология', 'Технология'), ('Химия', 'Химия'), ('Физика', 'Физика'), ('Информатика', 'Информатика'), ('Проектная деятельность', 'Проектная деятельность')], max_length=25)),
                ('school_сlass', models.CharField(max_length=100)),
                ('result', models.CharField(choices=[('1 место', '1 место'), ('2 место', '2 место'), ('3 место', '3 место'), ('Призёр', 'Призёр'), ('Победитель', 'Победитель'), ('Лауреат', 'Лауреат'), ('Участник', 'Участник'), ('Дипломат', 'Дипломат')], max_length=25)),
            ],
        ),
    ]
