# Generated by Django 4.1.4 on 2023-01-19 21:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reporting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='school_сlass',
            field=models.CharField(choices=[('а', 'а'), ('б', 'б'), ('в', 'в')], max_length=2),
        ),
    ]
