version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.prod
    command: >
      sh -c "cd /home/app/web/register/
      && python manage.py migrate --noinput
      && python manage.py collectstatic --noinput
      && gunicorn --reload -c ../configuration/gunicorn_config.py config.wsgi:application"
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/register/static
      - media_volume:/home/app/web/register/media
    env_file:
      - ${ENV}
    depends_on:
      - db

  db:
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    env_file:
      - ${ENV}
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  nginx:
    build: ./configuration/nginx
    volumes:
      - static_volume:/home/app/web/register/static
      - media_volume:/home/app/web/register/media
    ports:
      - 80:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume:
