version: '3.8'

services:
  web:
    build:
      context: ./register
      dockerfile: Dockerfile.prod
    command: gunicorn config.wsgi:application --timeout 300 --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    env_file:
      - .env
    depends_on:
      - db
  db:
    image: postgres:14-alpine
    volumes:
      - postgres_volume:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
  nginx:
    build: ./nginx
    volumes:
      - static_volume:/home/app/web/static
      - media_volume:/home/app/web/media
    ports:
      - 1337:80
    depends_on:
      - web

volumes:
  postgres_volume:
  static_volume:
  media_volume:
