# Generated by Django 4.1.4 on 2023-02-11 23:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0002_alter_student_school_сlass'),
        ('reporting', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contest',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student'),
        ),
    ]
