# Generated by Django 4.1.4 on 2023-03-16 20:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_class', models.CharField(max_length=50, verbose_name='Школьный класс')),
            ],
            options={
                'verbose_name': 'Школьный класс',
                'verbose_name_plural': 'Школьные классы',
            },
        ),
        migrations.CreateModel(
            name='StudentsBase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='students/')),
            ],
            options={
                'verbose_name': 'Список учащихся',
                'verbose_name_plural': 'Списки учащихся',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, unique=True, verbose_name='ФИО ученика')),
                ('is_learns', models.BooleanField(default=True, verbose_name='Проходит обучение')),
                ('school_сlass', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='school_сlass', to='students.class', verbose_name='Школьный класс')),
            ],
            options={
                'verbose_name': 'Ученик',
                'verbose_name_plural': 'Ученики',
            },
        ),
    ]
