# Generated by Django 4.1.4 on 2023-04-07 18:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import reporting.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateField(auto_now_add=True, verbose_name='Дата учёта мероприятия')),
                ('modified_date', models.DateField(auto_now=True, verbose_name='Дата последнего изменения учёта')),
                ('event_date', models.DateField(verbose_name='Дата проведения мероприятия')),
                ('title', models.CharField(max_length=100, verbose_name='Название мероприятия')),
                ('other', models.TextField(blank=True, null=True, verbose_name='Комментарии учителя')),
                ('teachers_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='ФИО ответсвенного руководителя')),
                ('stage', models.CharField(choices=[('Школьный', 'Школьный'), ('Районный', 'Районный'), ('Городской', 'Городской'), ('Региональный', 'Региональный'), ('Всероссийский', 'Всероссийский'), ('Международный', 'Международный')], max_length=25, verbose_name='Этап мероприятия')),
                ('direction', models.CharField(choices=[('Спорт', 'Спорт'), ('Образование', 'Образование'), ('Исскуство', 'Исскуство'), ('Культура', 'Культура'), ('Социальное', 'Социальное'), ('Олимпиада', 'Олимпиада')], max_length=25, verbose_name='Направление мероприятия')),
                ('subject', models.CharField(choices=[('Русский язык', 'Русский язык'), ('Литературное чтение', 'Литературное чтение'), ('Математика', 'Математика'), ('Окружающий мир', 'Окружающий мир'), ('Музыка', 'Музыка'), ('ИЗО', 'ИЗО'), ('Технология', 'Технология'), ('Физическая культура', 'Физическая культура'), ('Английский язык', 'Английский язык'), ('ОРКСЭ', 'ОРКСЭ'), ('Литература', 'Литература'), ('История', 'История'), ('Обществознание', 'Обществознание'), ('География', 'География'), ('Биология', 'Биология'), ('ОБЖ', 'ОБЖ'), ('Экономика', 'Экономика'), ('Технология', 'Технология'), ('Химия', 'Химия'), ('Физика', 'Физика'), ('Информатика', 'Информатика'), ('Проектная деятельность', 'Проектная деятельность')], max_length=25, verbose_name='Предметная область мероприятия')),
                ('scan_diploma', models.FileField(blank=True, null=True, upload_to=reporting.models.contest_diplom_scan_path, verbose_name='Скан диплома')),
                ('result', models.CharField(choices=[('1 место', '1 место'), ('2 место', '2 место'), ('3 место', '3 место'), ('Призёр', 'Призёр'), ('Победитель', 'Победитель'), ('Лауреат', 'Лауреат'), ('Участник', 'Участник'), ('Дипломат', 'Дипломат')], max_length=25, verbose_name='Результат мероприятия')),
                ('contest_creater', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Создатель учёта мероприятия')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='students.student', verbose_name='Ученик учавствующий в мероприятии')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
    ]
