# Generated by Django 4.1.4 on 2023-04-01 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('school_class', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True, verbose_name='Школьный класс')),
            ],
            options={
                'verbose_name': 'Школьный класс',
                'verbose_name_plural': 'Школьные классы',
            },
        ),
    ]
